package com.TroubleShooters.AcciAlert_server.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "hospitals")
public class Hospital {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long hospitalId; // Autogenerated, autoincremented hospital ID

    private String hospitalAddress; // Address of the hospital
    private String hospitalPincode; // Pincode of the hospital
    private String phoneNo; // Phone number of the hospital
}
