package com.TroubleShooters.AcciAlert_server.model;


import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "users")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long userId; // Autogenerated, autoincremented key

    private String vehicleNumber; // Vehicle number
    private String vehicleModel; // Name of the user's vehicle model
    private String vehicleType; // Type of vehicle (e.g., car, bike)

    @ElementCollection
    @CollectionTable(name = "emergency_contacts", joinColumns = @JoinColumn(name = "user_id"))
    @Column(name = "phone_number")
    private List<String> emergencyContacts; // List of emergency contact numbers

    private String name; // User's name
    private String gender; // Gender of user
    private String dateOfBirth; // Date of birth (YYYY-MM-DD format)
}
